WelcomeMOTD:
- '&1&lDragon&f&lCraft &d&lServer'
- '&1&lDoragon&f&lCraft &a&lNetwork'
MaintenanceMOTD:
- '&dServer: &9Maintenance!'
- '&4&lServer: &4&lIs Under maintenance!'
KickMessage: '&4Server Is Under Maintenance!'
BroadcastTime:
- 1
- 2
- 3
- 4
- 5
- 10
- 15
- 30
- 60
BroadcastSecondsMessage: '&4Maintenance Mode In %s Seconds!'
BroadcastSecondMessage: '&4Maintenance Mode In %s Second!'
BroadcastMinuteMessage: '&4Maintenance Mode In % Minute!'
BroadcastOnMaintenanceEnableMessage: '&4Server Is Now In Maintenance Mode'
BroadcastOnMaintenanceDisableMessage: '&bServer Is No Longer In Maintenance Mode'
CheckForUpdates: false
enabled: false
